export const Products = [
  {
    id: "1",
    name: "BarQuest Barrister",
    description: "Barrister Test",
    price: 14700,
    interval: "3 months",
    trialDays: 7,
    features: [
      "Questions with Commentary",
      "Unlimited Usage",
      "Real-Time Progress Tracking",
      "Mobile-Friendly Access",
      "Instant Feedback",
      "Regular Content Updates",
      "7 Days Risk-Free Trial",
    ],
  },
  {
    id: "2",
    name: "BarQuest Solicitor",
    description: "Solicitor Test",
    price: 14700,
    interval: "3 months",
    trialDays: 7,
    features: [
      "Questions with Commentary",
      "Unlimited Usage",
      "Real-Time Progress Tracking",
      "Mobile-Friendly Access",
      "Instant Feedback",
      "Regular Content Updates",
      "7 Days Risk-Free Trial",
    ],
  },
  {
    id: "3",
    name: "BarQuest Full",
    description: "Full Test",
    price: 24700,
    interval: "3 months",
    trialDays: 7,
    features: [
      "Questions with Commentary",
      "Unlimited Usage",
      "Real-Time Progress Tracking",
      "Mobile-Friendly Access",
      "Instant Feedback",
      "Regular Content Updates",
      "7 Days Risk-Free Trial",
    ],
  },
];
