export const barristerTopics = {
  "Professional Responsibility": [
    { topic: "Regulating the legal professions", pages: 1 },
    { topic: "Professionalism", pages: 5 },
    { topic: "Who is the client", pages: 15 },
    { topic: "Competence", pages: 23 },
    { topic: "Confidentiality", pages: 29 },
    { topic: "Conflicts of interest", pages: 35 },
    { topic: "Duty to the client", pages: 47 },
    { topic: "Fees and disbursements", pages: 55 },
    { topic: "Managing the client relationship", pages: 63 },
    { topic: "Withdrawal from representation", pages: 69 },
    { topic: "Duty to others", pages: 73 },
    { topic: "Advocacy", pages: 83 },
    { topic: "Practice management", pages: 91 },
    { topic: "Accounting, bank accounts, and bookkeeping", pages: 111 },
    { topic: "Indigenous peoples of Canada: history and current legal issues", pages: 133 }
  ],
  "Civil Litigation": [
    { topic: "Jurisdiction and organization of the courts of Ontario", pages: 143 },
    { topic: "The lawyer-client relationship", pages: 151 },
    { topic: "Privacy issues and litigation", pages: 153 },
    { topic: "Preliminary matters before commencing proceedings", pages: 155 },
    { topic: "Parties: persons who can sue and be sued", pages: 161 },
    { topic: "Joinder and interventions", pages: 171 },
    { topic: "Commencement of proceedings", pages: 179 },
    { topic: "Applications", pages: 185 },
    { topic: "Service of process", pages: 191 },
    { topic: "Pleadings", pages: 199 },
    { topic: "Disposition without trial", pages: 209 },
    { topic: "Subsidiary claims — counterclaims, crossclaims, and third-party claims", pages: 219 },
    { topic: "Motions", pages: 225 },
    { topic: "Discovery", pages: 235 },
    { topic: "Offers to settle and pre-trial procedures", pages: 261 },
    { topic: "Preparing for trial: marshalling the evidence", pages: 275 },
    { topic: "Trial procedure", pages: 285 },
    { topic: "Judgments, orders, appeals, enforcement, and costs", pages: 299 },
    { topic: "Alternative dispute resolution", pages: 315 },
    { topic: "Simplified procedure under Rule 76", pages: 327 }
  ],
  "Criminal Law": [
    { topic: "The classification of offences and trial jurisdiction", pages: 335 },
    { topic: "Investigative powers", pages: 349 },
    { topic: "Pre-trial release", pages: 365 },
    { topic: "Disclosure", pages: 377 },
    { topic: "Preliminary inquiries", pages: 385 },
    { topic: "Witnesses", pages: 391 },
    { topic: "Pre-trial and trial applications", pages: 399 },
    { topic: "Mental disorder", pages: 411 },
    { topic: "The trial", pages: 417 },
    { topic: "Sentencing", pages: 431 },
    { topic: "Appeals and bail pending appeals", pages: 449 },
    { topic: "Indigenous peoples and the criminal justice system", pages: 461 },
    { topic: "Youth criminal justice", pages: 467 },
    { topic: "Controlled Drugs and Substances Act", pages: 475 }
  ],
  "Family Law": [
    { topic: "Procedure and Family Law Rules", pages: 489 },
    { topic: "The law of divorce", pages: 513 },
    { topic: "Parenting orders", pages: 519 },
    { topic: "Matrimonial property", pages: 525 },
    { topic: "Child support", pages: 533 },
    { topic: "Spousal support", pages: 539 },
    { topic: "Cohabitation", pages: 543 },
    { topic: "Financial disclosure", pages: 547 },
    { topic: "Enforcement of support orders", pages: 555 },
    { topic: "Tax principles in family law", pages: 559 },
    { topic: "Alternative dispute resolution in family law", pages: 577 },
    { topic: "Domestic contracts", pages: 595 },
    { topic: "Representing a victim of domestic abuse", pages: 599 },
    { topic: "Child protection law", pages: 605 },
    { topic: "Aboriginal law in family law context", pages: 615 }
  ],
  "Public Law": [
    { topic: "Public law: basic principles", pages: 625 },
    { topic: "Practice before administrative tribunals", pages: 633 },
    { topic: "Judicial review of administrative action", pages: 639 },
    { topic: "Freedom of information and privacy", pages: 655 },
    { topic: "The division of powers", pages: 661 },
    { topic: "Interpreting the Charter", pages: 667 },
    { topic: "Proving a Charter claim", pages: 677 },
    { topic: "Procedure in constitutional cases", pages: 683 },
    { topic: "Aboriginal and treaty rights", pages: 693 }
  ]
};

export const solicitorTopics = {
  "Professional Responsibility": [
    { topic: "Regulating the legal professions", pages: 1 },
    { topic: "Professionalism", pages: 5 },
    { topic: "Who is the client", pages: 15 },
    { topic: "Competence", pages: 23 },
    { topic: "Confidentiality", pages: 29 },
    { topic: "Conflicts of interest", pages: 35 },
    { topic: "Duty to the client", pages: 47 },
    { topic: "Fees and disbursements", pages: 55 },
    { topic: "Managing the client relationship", pages: 63 },
    { topic: "Withdrawal from representation", pages: 69 },
    { topic: "Duty to others", pages: 73 },
    { topic: "Advocacy", pages: 83 },
    { topic: "Practice management", pages: 91 },
    { topic: "Accounting, bank accounts, and bookkeeping", pages: 111 },
    { topic: "Indigenous peoples of Canada: history and current legal issues", pages: 133 }
  ],
  "Business Law": [
    { topic: "Methods of carrying on business", pages: 143 },
    { topic: "Partnerships", pages: 153 },
    { topic: "Taxation of corporations and their shareholders", pages: 163 },
    { topic: "Income tax administration and enforcement", pages: 195 },
    { topic: "The creation of the corporation", pages: 209 },
    { topic: "Directors, officers, and shareholders", pages: 217 },
    { topic: "Shareholder agreements", pages: 227 },
    { topic: "Corporate changes", pages: 243 },
    { topic: "Securities laws", pages: 273 },
    { topic: "Debt financing and secured transactions", pages: 287 },
    { topic: "Searches and opinions", pages: 303 },
    { topic: "Unsecured creditors' rights", pages: 313 },
    { topic: "Secured creditors' rights", pages: 337 },
    { topic: "Employees", pages: 369 },
    { topic: "Domestic and international sale of goods", pages: 395 },
    { topic: "Privacy law", pages: 415 },
    { topic: "Corporate reorganizations under insolvency laws", pages: 427 },
    { topic: "The purchase and sale of a private business", pages: 447 }
  ],
  "Estate Planning": [
    { topic: "Will planning, drafting, and execution", pages: 479 },
    { topic: "Powers of attorney", pages: 499 },
    { topic: "Court appointment of guardians", pages: 509 },
    { topic: "Guardians, decision-making responsibility, Children's Law Reform Act", pages: 517 },
    { topic: "Taxation at death", pages: 521 },
    { topic: "Trusts and estate planning", pages: 529 },
    { topic: "Impact of the Family Law Act on estate administration", pages: 539 },
    { topic: "Administration of estates", pages: 551 },
    { topic: "Estate litigation", pages: 579 },
    { topic: "Claims by common-law spouses", pages: 597 },
    { topic: "Wills and estates under the Indian Act", pages: 599 }
  ],
  "Real Estate": [
    { topic: "Agreement of purchase and sale", pages: 607 },
    { topic: "Land registration in Ontario", pages: 637 },
    { topic: "Title searching", pages: 643 },
    { topic: "Subdivision control", pages: 663 },
    { topic: "The survey", pages: 677 },
    { topic: "Requisitions", pages: 681 },
    { topic: "Standard loan transaction", pages: 689 },
    { topic: "Preparation for closing, closing, and post-closing", pages: 739 },
    { topic: "Commercial real estate transactions", pages: 863 },
    { topic: "Commercial leasing", pages: 887 },
    { topic: "Construction liens", pages: 899 },
    { topic: "Indigenous property issues", pages: 911 },
    { topic: "Fraud in real estate transactions", pages: 919 }
  ]
};

export const daysOfWeek = [
  { id: "monday", label: "Monday" },
  { id: "tuesday", label: "Tuesday" },
  { id: "wednesday", label: "Wednesday" },
  { id: "thursday", label: "Thursday" },
  { id: "friday", label: "Friday" },
  { id: "saturday", label: "Saturday" },
  { id: "sunday", label: "Sunday" }
];
