name: Create Sentry Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: "barquestinc"
          SENTRY_PROJECT: "barquest"
        with:
          environment: production

      - name: Install Sentry CLI
        run: npm ci

      - name: Create Sentry release
        run: |
          # Create a new release on Sentry
          npx sentry-cli releases new "$GITHUB_SHA"

          # Associate commits with the release
          npx sentry-cli releases set-commits --auto "$GITHUB_SHA"

          # Finalize the release
          npx sentry-cli releases finalize "$GITHUB_SHA"

          # (Optional) Upload source maps, adjust path accordingly
          npx sentry-cli releases files "$GITHUB_SHA" upload-sourcemaps ./dist

      - name: Deploy Sentry release
        run: |
          # Notify Sentry about the deployment
          npx sentry-cli releases deploys "$GITHUB_SHA" new -e production
